spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/covid-db
    username: postgres
    password: admin
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
       ddl-auto: update
  liquibase:
    enabled: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
          
